"""
Telemetry point model.
A single sensor reading captured during a test session.
"""

from datetime import datetime
from pydantic import BaseModel, Field, field_validator
from typing import Literal


class GeoPoint(BaseModel):
    """3D geographic position."""
    
    latitude: float = Field(..., ge=-90, le=90, description="Decimal degrees")
    longitude: float = Field(..., ge=-180, le=180, description="Decimal degrees")
    altitude_msl_m: float = Field(..., ge=-500, le=20000, description="Meters above mean sea level")


class Attitude(BaseModel):
    """Aircraft orientation in degrees."""
    
    roll: float = Field(..., ge=-180, le=180)
    pitch: float = Field(..., ge=-90, le=90)
    yaw: float = Field(..., ge=0, lt=360)


class BatteryState(BaseModel):
    """Battery-specific telemetry for electric/hybrid aircraft."""
    
    voltage_v: float = Field(..., gt=0, le=1000, description="Total pack voltage")
    current_a: float = Field(..., ge=-1000, le=1000, description="Positive=discharge, negative=charge")
    soc_percent: float = Field(..., ge=0, le=100, description="State of charge, 0-100")
    temperature_c: float = Field(..., ge=-40, le=80, description="Cell or pack temperature")
    
    @field_validator("voltage_v")
    @classmethod
    def voltage_reasonable(cls, v: float) -> float:
        """eVTOL battery packs are typically 400-800V. Flag suspicious values."""
        if v < 10:
            raise ValueError(f"voltage_v ({v}) seems too low for eVTOL pack")
        return v


class MotorState(BaseModel):
    """Single motor/propulsor state."""
    
    motor_id: str = Field(..., min_length=1, max_length=16)
    rpm: float = Field(..., ge=0, le=20000)
    current_a: float = Field(..., ge=0, le=500)
    temperature_c: float = Field(..., ge=-40, le=200)


class IMUState(BaseModel):
    """Inertial measurement unit raw readings."""
    
    accel_x_ms2: float = Field(..., ge=-100, le=100, description="X-axis acceleration, m/s²")
    accel_y_ms2: float = Field(..., ge=-100, le=100)
    accel_z_ms2: float = Field(..., ge=-100, le=100)
    gyro_x_dps: float = Field(..., ge=-2000, le=2000, description="X-axis rotation rate, deg/s")
    gyro_y_dps: float = Field(..., ge=-2000, le=2000)
    gyro_z_dps: float = Field(..., ge=-2000, le=2000)


class GPSState(BaseModel):
    """GPS receiver state."""
    
    fix_type: Literal["none", "2d", "3d", "dgps", "rtk"] = "none"
    satellites: int = Field(..., ge=0, le=50)
    hdop: float = Field(..., ge=0, le=50, description="Horizontal dilution of precision, lower=better")


class TelemetryPoint(BaseModel):
    """
    A single telemetry sample captured at a specific moment during a test session.
    
    Not all fields are required. A battery test might only send BatteryState.
    A flight test might send everything.
    """
    
    point_id: str | None = Field(
        default=None,
        description="Unique ID. Auto-generated by server if not provided.",
    )
    
    session_id: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Reference to TestSession.session_id",
    )
    
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When this sample was recorded (sensor time)",
    )
    
    position: GeoPoint | None = Field(
        default=None,
        description="GPS position, if available",
    )
    
    attitude: Attitude | None = Field(
        default=None,
        description="Aircraft attitude, if available",
    )
    
    battery: BatteryState | None = Field(
        default=None,
        description="Battery state, for electric/hybrid propulsion",
    )
    
    motors: list[MotorState] | None = Field(
        default=None,
        max_length=16,
        description="Motor states. One per propulsor.",
    )
    
    imu: IMUState | None = Field(
        default=None,
        description="Raw IMU readings",
    )
    
    gps: GPSState | None = Field(
        default=None,
        description="GPS receiver state",
    )
    
    @field_validator("motors")
    @classmethod
    def motor_count_reasonable(cls, v: list[MotorState] | None) -> list[MotorState] | None:
        """eVTOLs typically have 4-12 motors. Flag suspicious counts."""
        if v is not None and len(v) > 12:
            raise ValueError(f"Motor count ({len(v)}) exceeds typical eVTOL maximum (12)")
        return v


# --- Test it ---
if __name__ == "__main__":
    from datetime import timedelta
    
    # Minimal: battery-only telemetry (ground test)
    t1 = TelemetryPoint(
        session_id="ts-001",
        battery=BatteryState(
            voltage_v=540.0,
            current_a=45.2,
            soc_percent=87.5,
            temperature_c=35.0,
        ),
    )
    print("Battery-only telemetry:")
    print(t1.model_dump_json(indent=2))
    
    # Full flight telemetry
    now = datetime.now()
    t2 = TelemetryPoint(
        session_id="ts-002",
        timestamp=now,
        position=GeoPoint(latitude=17.4065, longitude=78.4772, altitude_msl_m=542.0),
        attitude=Attitude(roll=2.5, pitch=-1.0, yaw=95.0),
        battery=BatteryState(voltage_v=538.5, current_a=120.0, soc_percent=72.0, temperature_c=42.0),
        motors=[
            MotorState(motor_id="M1", rpm=1850, current_a=28.5, temperature_c=55.0),
            MotorState(motor_id="M2", rpm=1860, current_a=29.0, temperature_c=56.0),
            MotorState(motor_id="M3", rpm=1845, current_a=28.0, temperature_c=54.5),
            MotorState(motor_id="M4", rpm=1855, current_a=28.8, temperature_c=55.5),
        ],
        imu=IMUState(
            accel_x_ms2=0.2, accel_y_ms2=-0.1, accel_z_ms2=9.8,
            gyro_x_dps=0.5, gyro_y_dps=-0.3, gyro_z_dps=0.1,
        ),
        gps=GPSState(fix_type="3d", satellites=12, hdop=1.2),
    )
    print(f"\nFull flight telemetry (4 motors):")
    print(f"Position: {t2.position.latitude}, {t2.position.longitude}")
    print(f"Battery SOC: {t2.battery.soc_percent}%")
    print(f"Motor count: {len(t2.motors)}")
    
    # Invalid: too many motors
    print("\n--- Testing too many motors ---")
    try:
        bad = TelemetryPoint(
            session_id="ts-001",
            motors=[MotorState(motor_id=f"M{i}", rpm=1000, current_a=10, temperature_c=30) for i in range(20)],
        )
    except ValueError as e:
        print(f"Caught: {e}")
    
    # Invalid: battery voltage too low
    print("\n--- Testing suspicious battery voltage ---")
    try:
        bad2 = TelemetryPoint(
            session_id="ts-001",
            battery=BatteryState(voltage_v=3.7, current_a=0, soc_percent=50, temperature_c=25),
        )
    except ValueError as e:
        print(f"Caught: {e}")